# Generated by Django 2.2 on 2019-09-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0003_auto_20190918_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotstiming',
            name='day',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slotstiming',
            name='event',
            field=models.TextField(blank=True, null=True),
        ),
    ]
